metadata/objects/App_Log__c.object
<CustomObject>
    <description>Object used to store any kind of application logs.</description>
    <fields>
        <fullName>Action__c</fullName>
        <inlineHelpText>Action within the module that produced this log.</inlineHelpText>
        <label>Action</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>App_Task_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The app log, during whose processing this log entry was created</inlineHelpText>
        <label>App Task</label>
        <referenceTo>App_Task__c</referenceTo>
        <relationshipLabel>App Logs</relationshipLabel>
        <relationshipName>App_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Details1__c</fullName>
        <inlineHelpText>Details stores any log or additional details associated with the tx log. There are 5 details fields, Details1 till Details5.</inlineHelpText>
        <label>Details1</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Module__c</fullName>
        <inlineHelpText>The module which generated this tx log</inlineHelpText>
        <label>Module</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Id__c</fullName>
        <label>Record Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sobject__c</fullName>
        <inlineHelpText>If this tx log was generated as part of processing a record of a particular object, this field would indicate that object.</inlineHelpText>
        <label>Sobject</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Debug</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Value1__c</fullName>
        <inlineHelpText>Value fields can be used to store any additional information relevant to transaction, which this log is associated with.</inlineHelpText>
        <label>Value1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value2__c</fullName>
        <label>Value2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value3__c</fullName>
        <label>Value3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value4__c</fullName>
        <label>Value4</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value5__c</fullName>
        <label>Value5</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>App Log</label>
    <nameField>
        <displayFormat>APL-{0000000000}</displayFormat>
        <label>App Log#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>App Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/objects/App_Task__c.object
<CustomObject>
    <description>Object used to store the information about a task that needs to be processed later. Record Indicates a unit of work that is done synchronously/asynchronously. The unit of work could be associated with ab object and/or record or it need not be associated with any object.</description>
    <fields>
        <fullName>Action__c</fullName>
        <inlineHelpText>The action this task is associated with.</inlineHelpText>
        <label>Action</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <inlineHelpText>Indicates any external id associated with this task</inlineHelpText>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <inlineHelpText>Any applicable processing message</inlineHelpText>
        <label>Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Module__c</fullName>
        <inlineHelpText>The module to which this task is associated with.</inlineHelpText>
        <label>Module</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Id__c</fullName>
        <inlineHelpText>If this task is associated with a particular object, then indicates the record of that object.</inlineHelpText>
        <label>Record Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sobject__c</fullName>
        <inlineHelpText>Sobject name to which this task is associated with.</inlineHelpText>
        <label>Sobject</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value1__c</fullName>
        <inlineHelpText>Value1-5 fields are used to capture any individual values associated with this task.</inlineHelpText>
        <label>Value1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value2__c</fullName>
        <label>Value2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value3__c</fullName>
        <label>Value3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value4__c</fullName>
        <label>Value4</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value5__c</fullName>
        <label>Value5</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>App Task</label>
    <nameField>
        <displayFormat>APT-{0000000000}</displayFormat>
        <label>App Task#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>App Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/classes/AppLogBuilderTest.cls
@IsTest
public class AppLogBuilderTest {
	static Assert assert = sf.assert;
    
    testmethod public static void test_appLogBuilder() {
        TestUtils.setCurrentDateTime(DateTime.newInstance(2017, 10, 01));
        
        App_Task__c appTask = new App_Task__c(Module__c='test', Action__c='test');
        insert appTask;
        
        AppLogBuilder appLog = Sf.newAppLog()
            .module('UnitTest')
            .action('LogTest')
            .typeDebug()
            .message('Testing')
            .value1('value1')
            .value2('value2')
            .value3('value3')
            .value4('value4')
            .value5('value5')
            .appTask(appTask)
            .externalId('some external id')
            .record(appTask)
			.log('Starting processing')
            .log('Some error', new LibshareException())
            .typeError();
            
        App_Log__c alObj = appLog.getLogRecord();
		appLog.setLogRecord(alObj);
        
        assert.that(alObj.Action__c).isEqualsTo('LogTest');
        assert.that(alObj.Module__c).isEqualsTo('UnitTest');
        assert.that(alObj.Type__c).isEqualsTo('Error');
        assert.that(alObj.Message__c).isEqualsTo('Some error');
        assert.that(alObj.Value1__c).isEqualsTo('value1');
        assert.that(alObj.Value2__c).isEqualsTo('value2');
        assert.that(alObj.Value3__c).isEqualsTo('value3');
        assert.that(alObj.Value4__c).isEqualsTo('value4');
        assert.that(alObj.Value5__c).isEqualsTo('value5');
        assert.that(alObj.External_Id__c).isEqualsTo('some external id');
        assert.that(alObj.App_Task_Id__c).isEqualsTo(appTask.id);
        assert.that(alObj.Record_Id__c).isEqualsTo(appTask.id);
        assert.that(alObj.Sobject__c).isEqualsTo('lib__App_Task__c');
        assert.that(alObj.Details1__c).isNotBlank();
        
		appLog.stash();
        assert.that([select id from app_log__c].size()).isEqualsTo(0);
        
		appLog.save();
        assert.that([select id from app_log__c].size()).isEqualsTo(1);
    }
}