metadata/objects/App_Log__c.object
<CustomObject>
    <description>Object used to store any kind of application logs.</description>
    <fields>
        <fullName>Action__c</fullName>
        <inlineHelpText>Action within the module that produced this log.</inlineHelpText>
        <label>Action</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>App_Task_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The app log, during whose processing this log entry was created</inlineHelpText>
        <label>App Task</label>
        <referenceTo>App_Task__c</referenceTo>
        <relationshipLabel>App Logs</relationshipLabel>
        <relationshipName>App_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Module__c</fullName>
        <inlineHelpText>The module which generated this tx log</inlineHelpText>
        <label>Module</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Id__c</fullName>
        <label>Record Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sobject__c</fullName>
        <inlineHelpText>If this tx log was generated as part of processing a record of a particular object, this field would indicate that object.</inlineHelpText>
        <label>Sobject</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Debug</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Value1__c</fullName>
        <inlineHelpText>Value fields can be used to store any additional information relevant to transaction, which this log is associated with.</inlineHelpText>
        <label>Value1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value2__c</fullName>
        <label>Value2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value3__c</fullName>
        <label>Value3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value4__c</fullName>
        <label>Value4</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value5__c</fullName>
        <label>Value5</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>App Log</label>
    <nameField>
        <displayFormat>APL-{0000000000}</displayFormat>
        <label>App Log#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>App Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/objects/App_Task__c.object
<CustomObject>
    <description>Object used to store the information about a task that needs to be processed later. Record Indicates a unit of work that is done synchronously/asynchronously. The unit of work could be associated with ab object and/or record or it need not be associated with any object.</description>
    <fields>
        <fullName>Action__c</fullName>
        <inlineHelpText>The action this task is associated with.</inlineHelpText>
        <label>Action</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <inlineHelpText>Indicates any external id associated with this task</inlineHelpText>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <inlineHelpText>Any applicable processing message</inlineHelpText>
        <label>Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Module__c</fullName>
        <inlineHelpText>The module to which this task is associated with.</inlineHelpText>
        <label>Module</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Id__c</fullName>
        <inlineHelpText>If this task is associated with a particular object, then indicates the record of that object.</inlineHelpText>
        <label>Record Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sobject__c</fullName>
        <inlineHelpText>Sobject name to which this task is associated with.</inlineHelpText>
        <label>Sobject</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value1__c</fullName>
        <inlineHelpText>Value1-5 fields are used to capture any individual values associated with this task.</inlineHelpText>
        <label>Value1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value2__c</fullName>
        <label>Value2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value3__c</fullName>
        <label>Value3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value4__c</fullName>
        <label>Value4</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value5__c</fullName>
        <label>Value5</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>App Task</label>
    <nameField>
        <displayFormat>APT-{0000000000}</displayFormat>
        <label>App Task#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>App Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/classes/AppLogBuilder.cls
global class AppLogBuilder {
	private App_Log__c appLog = new App_Log__c();
    private static Utils u = new Utils();
    
    public AppLogBuilder() {
    }
    
    global AppLogBuilder module(String value) {
        appLog.Module__c = value;
        return this;
    }

    global AppLogBuilder action(String action) {
        appLog.Action__c = action;
        return this;
    }

    global AppLogBuilder typeError() {
        appLog.Type__c = 'Error';
        return this;
    }
    
    global AppLogBuilder typeDebug() {
        appLog.Type__c = 'Debug';
        return this;
    }
    
    global AppLogBuilder appTask(App_Task__c value) {
        return appTask(value.id);
    }

    global AppLogBuilder appTask(Id value) {
        appLog.App_Task_Id__c = value;
        return this;
    }

    global AppLogBuilder externalId(String value) {
        appLog.External_Id__c = value;
        return this;
    }

    global AppLogBuilder message(String value) {
        appLog.Message__c = value;
        return this;
    }

    global AppLogBuilder record(Sobject value) {
        appLog.Record_Id__c = value.id;
        appLog.Sobject__c = u.getSobject(value);
        return this;
    }

    global AppLogBuilder value1(String value) {
        appLog.Value1__c = value;
        return this;
    }

    global AppLogBuilder value2(String value) {
        appLog.Value2__c = value;
        return this;
    }

    global AppLogBuilder value3(String value) {
        appLog.Value3__c = value;
        return this;
    }

    global AppLogBuilder value4(String value) {
        appLog.Value4__c = value;
        return this;
    }

    global AppLogBuilder value5(String value) {
        appLog.Value5__c = value;
        return this;
    }
    
    global AppLogBuilder append(String value) {
		Sf.appLogger.append(appLog, value);
        return this;
    }
    
    global AppLogBuilder append(String message, Exception e) {
		Sf.appLogger.append(appLog, message, e);
        return this;
    }

    global App_Log__c getAppLog() {
        return appLog;
    }
    
    global AppLogBuilder setAppLog(App_Log__c appLog) {
        this.appLog = appLog;
        return this;
    }

    global void save() {
        Sf.appLogger.save(appLog);
    }

    global void stash() {
        Sf.appLogger.stash(appLog);
    }
}