metadata/objects/App_Log__c.object
<CustomObject>
    <description>Object used to store any kind of application logs.</description>
    <fields>
        <fullName>Action__c</fullName>
        <inlineHelpText>Action within the module that produced this log.</inlineHelpText>
        <label>Action</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>App_Task_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The app log, during whose processing this log entry was created</inlineHelpText>
        <label>App Task</label>
        <referenceTo>App_Task__c</referenceTo>
        <relationshipLabel>App Logs</relationshipLabel>
        <relationshipName>App_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Details1__c</fullName>
        <inlineHelpText>Details stores any log or additional details associated with the tx log. There are 5 details fields, Details1 till Details5.</inlineHelpText>
        <label>Details1</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Details2__c</fullName>
        <label>Details2</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Details3__c</fullName>
        <label>Details3</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Details4__c</fullName>
        <label>Details4</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Details5__c</fullName>
        <label>Details5</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Module__c</fullName>
        <inlineHelpText>The module which generated this tx log</inlineHelpText>
        <label>Module</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Id__c</fullName>
        <label>Record Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record__c</fullName>
        <formula>If(Not(IsBlank(Record_Id__c)), HYPERLINK(&apos;/&apos; + Record_Id__c, Record_Id__c), null)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Record</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sobject__c</fullName>
        <inlineHelpText>If this tx log was generated as part of processing a record of a particular object, this field would indicate that object.</inlineHelpText>
        <label>Sobject</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Debug</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Value1__c</fullName>
        <inlineHelpText>Value fields can be used to store any additional information relevant to transaction, which this log is associated with.</inlineHelpText>
        <label>Value1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value2__c</fullName>
        <label>Value2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value3__c</fullName>
        <label>Value3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value4__c</fullName>
        <label>Value4</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value5__c</fullName>
        <label>Value5</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>App Log</label>
    <nameField>
        <displayFormat>APL-{0000000000}</displayFormat>
        <label>App Log#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>App Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/classes/AppLoggerTest.cls
@IsTest
public class AppLoggerTest {
	static Assert assert = sf.assert;
	
    testmethod public static void test_logError() {
        TestUtils.setCurrentDateTime(DateTime.newInstance(2017, 01, 01));
        
        Sf.appLogger.saveError('Module', 'Action', 'Something terrible happened.', new Utils().createTestException());
        
        App_Log__c alObj = queryAppLogs().get(0);
        assert.that(alObj.Module__c).isEqualsTo('Module');
        assert.that(alObj.Action__c).isEqualsTo('Action');
        assert.that(alObj.Type__c).isEqualsTo('Error');
        assert.that(alObj.Message__c).isEqualsTo('Something terrible happened.');
        assert.that(alObj.Details1__c).isNotBlank();
        
    }
    
    private static List<App_Log__c> queryAppLogs() {
        return [select Id, Name, Action__c, App_Task_Id__c, Details1__c, Details2__c, Details3__c, Details4__c, Details5__c, 
            External_Id__c, Message__c, Module__c, Record__c, Record_Id__c, Sobject__c, Type__c, Value1__c, 
            Value2__c, Value3__c, Value4__c, Value5__c, OwnerId from App_Log__c];
    }
    
}