metadata/objects/Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom settings to store all general purpose settings for the application. These settings should be accessed via dlib.sf.appsettings.</description>
    <fields>
        <fullName>Env_Specific__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, this setting should not be copied over from one environment to another.</inlineHelpText>
        <label>Env Specific</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <inlineHelpText>The setting value can be stored in one or more value{n}__c fields depending on big that value is. The values are Value1__c, Value2__c etc.,</inlineHelpText>
        <label>Value</label>
        <type>TextArea</type>
    </fields>
    <label>Settings</label>
</CustomObject>

metadata/classes/SettingsPostSandboxCopyHandlerTest.cls
@IsTest
public class SettingsPostSandboxCopyHandlerTest {
    testmethod public static void test_postcopy() {
		Settings__c setting = new Settings__c();
        setting.name = 'envtest';
        setting.Value__c = 'value1';
        setting.Env_Specific__c = true;
		
		insert setting;

		setting = new Settings__c();
        setting.name = 'test';
        setting.Value__c = 'value2';
        setting.Env_Specific__c = false;
		
		insert setting;

        new SettingsPostSandboxCopyHandler().runApexClass(null);
        
        Sf.assert.that(Sf.settings.getString('envtest', null)).isNull();

        Sf.assert.that(Sf.settings.getString('test', null)).isEqualsTo('value2');
    }
}